//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Late.Domain.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Departures {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Departures() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Late.Domain.Tests.Resources.Departures", typeof(Departures).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;clr&quot; href=&quot;/pj/ldbdetails/H5U1l1ddtyWf%23rZ39eVBPw%3D%3D/?board=dep&quot;&gt;&lt;span class=&quot;time em&quot;&gt;11:42&lt;br&gt;&lt;small&gt;On time&lt;/small&gt;&lt;/span&gt;&lt;span class=&quot;station&quot;&gt;London Bridge&lt;/span&gt;&lt;span class=&quot;platform&quot;&gt;&lt;small&gt;Platform&lt;/small&gt;&lt;br&gt;1&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string BrokenOnTime {
            get {
                return ResourceManager.GetString("BrokenOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//WAPFORUM//DTD XHTML Mobile 1.0//EN&quot; &quot;http://www.wapforum.org/DTD/xhtml-mobile10.dtd&quot;&gt;
        ///
        ///
        ///
        ///
        ///
        ///
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;meta name=&quot;viewport&quot; content=&quot;maximum-scale=1.0,width=device-width,initial-scale=1.0, user-scalable=0&quot; /&gt;
        ///&lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///&lt;meta http-equiv=&quot;expires&quot; content=&quot;0&quot; /&gt;
        ///&lt;meta http-equiv=&quot;Pragma&quot; content=&quot;no-c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrokenSummary {
            get {
                return ResourceManager.GetString("BrokenSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;clr&quot; href=&quot;/pj/ldbdetails/atwCLq1z66nxyALPitRrVw%3D%3D/?board=dep&quot;&gt;&lt;span class=&quot;time em&quot;&gt;13:33&lt;br /&gt;&lt;small class=&quot;delayed&quot;&gt;Cancelled&lt;/small&gt;&lt;/span&gt;&lt;/span&gt;&lt;span class=&quot;station&quot;&gt;London Charing Cross&lt;br /&gt;&lt;small&gt; via Tonbridge&lt;/small&gt;&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;clr&quot; href=&quot;/pj/ldbdetails/Bj0qjNzG%23M6Hrijqdpj02w%3D%3D/?board=dep&quot;&gt;&lt;span class=&quot;time em&quot;&gt;17:17&lt;br/&gt;&lt;small&gt;17:19&lt;/small&gt;&lt;/span&gt;&lt;/span&gt;&lt;span class=&quot;station&quot;&gt;Crystal Palace&lt;/span&gt;&lt;span class=&quot;platform&quot;&gt;&lt;small&gt;Platform&lt;/small&gt;&lt;br/&gt;2&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string ExpectedDelay {
            get {
                return ResourceManager.GetString("ExpectedDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;clr&quot; href=&quot;/pj/ldbdetails/H5U1l1ddtyWf%23rZ39eVBPw%3D%3D/?board=dep&quot;&gt;&lt;span class=&quot;time em&quot;&gt;11:42&lt;br/&gt;&lt;small&gt;On time&lt;/small&gt;&lt;/span&gt;&lt;/span&gt;&lt;span class=&quot;station&quot;&gt;London Bridge&lt;/span&gt;&lt;span class=&quot;platform&quot;&gt;&lt;small&gt;Platform&lt;/small&gt;&lt;br/&gt;1&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string OnTime {
            get {
                return ResourceManager.GetString("OnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a class=&quot;clr&quot; href=&quot;/pj/ldbdetails/QYlfZX24XdmOEB7R7ULn7g%3D%3D/?board=dep&quot;&gt;&lt;span class=&quot;time em&quot;&gt;13:15&lt;br /&gt;&lt;small class=&quot;delayed&quot;&gt;Delayed&lt;/small&gt;&lt;/span&gt;&lt;/span&gt;&lt;span class=&quot;station&quot;&gt;Reigate&lt;/span&gt;&lt;/a&gt;.
        /// </summary>
        internal static string UnknownDelay {
            get {
                return ResourceManager.GetString("UnknownDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//WAPFORUM//DTD XHTML Mobile 1.0//EN&quot; &quot;http://www.wapforum.org/DTD/xhtml-mobile10.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;maximum-scale=1.0,width=device-width,initial-scale=1.0, user-scalable=0&quot; /&gt;
        ///    &lt;meta name=&quot;format-detection&quot; content=&quot;telephone=no&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;expires&quot; content=&quot;0&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Pragma&quot; conte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ValidSummary {
            get {
                return ResourceManager.GetString("ValidSummary", resourceCulture);
            }
        }
    }
}
